name: htnup
author: laco0416 <laco0416@gmail.com>
homepage: https://github.com/laco0416/htnup.dart
description:
  Hatena blog entry uploader
version: 0.1.0
dependencies:
  args: ">=0.12.0+1 <0.13.0"
  path: ">=1.2.2 <2.0.0"
  xml: ">=2.1.3 <3.0.0"
  http: ">=0.11.1+1 <0.12.0"
  utf:  ">=0.9.0+1 <0.10.0"